### ISSUE TITLE
Parse pokemon links in the announcement

### ISSUE THREAD

**Issue by coyotte508** [po-devs/webclient#1]
In the webclient po announcement of the webclient, the dratini/larvitar sprites appear as a missing file.

You can access po images that way:

http://pokemon-online.eu/images/pokemon/[path]

For a bw bulbasaur it would be http://pokemon-online.eu/images/pokemon/black-white/1.png
For its back image, http://pokemon-online.eu/images/pokemon/black-white/back/1.png

Basically if you open bin/db/pokes/[XG]/sprites.zip you'll see how the path is organized. It's the same as veekun sprite urls, and there are more gens than in the PO client.

The goal here is to parse and replace  things like &lt;img src="pokemon:147&gen=2" /&gt; by &lt;img src="htttp://pokemon-online.eu/images/pokemon/crystal/2.png" /&gt;

**Comment by HRDepartment** [comment]
Could use $("img", message) on every new incoming html/announcement along with some other jQuery functions to "fix" this. How strict is PO with whitespace in this tag?

**Comment by coyotte508** [comment]
This really depends on the people editing the server announcement, the number of whitespace they put in the img tag. A regexp on src="pokemon:xx" would suffice to find the link to replace, but cleaner options (with jquery) can also be used.

**Comment by HRDepartment** [comment]
Of course that (regexp) wouldn't work with shiny/backsprites/etc. because they don't have a specific order.

**Comment by coyotte508** [comment]
The regexp would suffice to **find** the link to replace, and after of course it needs to be parsed.

**Comment by lamperi** [comment]
The correct way is to get the img element, and then change the src attribute by using javascript or jquery. HTML cannot be parsed with a regexp. Use the browser's html engine for that.

**Comment by lamperi** [comment]
Here's my implementation, but it is still lacking on the support as pokemon:-protocol was implemented and only in the announcement.

https://github.com/lamperi/webclient/commit/7552b463081e2ff4b5e076a24284fb51d6383d47

**Comment by coyotte508** [comment]
Nicely done

**Comment by HRDepartment** [comment]
I was on another server today which used img:pokemon (it works fine), but, they used a black background in the announcement. The images weren't transparent like they are with the client so it looked pretty weird (white backgrounds around the pokemon).

**Comment by coyotte508** [comment]
I guess I'll upload the sprites from the client then. or run all the images through imageconvert :x
