### ISSUE TITLE
RelayStation doesn't send the player's id

### ISSUE THREAD

**Issue by HRDepartment** [po-devs/webclient#17]
The relay station doesn't send a player's id in the playerlist - instead it sends something like this:
playerslist|{"id":{"auth":0,"color":"#000000","name":"."}}

**Comment by coyotte508** [comment]
This is an issue for the c++ side, not the webclient.

Fixed https://github.com/coyotte508/pokemon-online/commit/f609a7014b3bf3bcaf7220bb7af0365f197766ef
