### ISSUE TITLE
Change the slicing policy of chat logs

### ISSUE THREAD

**Issue by coyotte508** [po-devs/webclient#20]
Currently chat logs are sliced according to the number of "\n"

This can create trouble if a message contains \n inside html tags.

The solution is to insert each chat line undex a &lt;div> tag instead of using &lt;br/>:

```
chat.innerHTML += "<div class='chat-line'>"+line+"</div>"
```

Then when slicing, instead of splitting/taking the last 500, you can do something like $(chat).html($(chat).find("> div[class='chat-line']").slice(-500)) or whatever works.

**Comment by HRDepartment** [comment]
Don't use [class='...'] to select tags by classes... Use div.chat-line instead.

**Comment by coyotte508** [comment]
right
