### ISSUE TITLE
Add auto-complete to channels

### ISSUE THREAD

**Issue by coyotte508** [po-devs/webclient#21]
Add auto-complete to the "Join channel..." tab.

Please make it nice and clean

**Comment by HRDepartment** [comment]
Is there a command for channel creation/destruction.

**Comment by coyotte508** [comment]
yes and it's already handled by the webclient.

Channels.addChannel and Channels.removeChannel iirc

There is also a channel name change event that is dealt by the webclient

But imo autocomplete should only trigger when the player list has the focus, so you only need to check the names in the channel list at that point. No need to deal with adding/removing channels when autocomplete is running or not running, adding code at a lot of different places for that... well i'm not sure it's worth it. Imo detect when we give focus to player list and then refresh the autocomplete list is best.

Jquery plugin: http://api.jqueryui.com/autocomplete/

**Comment by HRDepartment** [comment]
Done.

**Comment by coyotte508** [comment]
https://github.com/coyotte508/webclient/commit/72f9127338a8a3cb1fbd0ce7f4f607e319145f19
