### ISSUE TITLE
Detect links with po: protocol

### ISSUE THREAD

**Issue by coyotte508** [po-devs/webclient#27]
So you can detect links that make you join a channel (when issue #26 is done).

I don't know if there's a clean easy way to do this, the hard way would be something like:

```
$('a[href^="[po:"]').live("click", function(...){...; return false;});
```

where all the other initialisations (players, channels, ...) are.

**Comment by HRDepartment** [comment]
Can't you just reuse the code in js/formatting.js?

**Comment by coyotte508** [comment]
you could, too

**Comment by HRDepartment** [comment]
Taking this issue along with #26.
