### ISSUE TITLE
Webclient doesn't remove channels when reconnecting (disconnect -> connect)

### ISSUE THREAD

**Issue by HRDepartment** [po-devs/webclient#29]
It doesn't clear any other data either..

**Comment by coyotte508** [comment]
Disconnect/Reconnect isn't handled at all atm. It's a thought for the future, when more stuff is done.

**Comment by coyotte508** [comment]
Ok, you can clear data/channels, only when reconnecting though

**Comment by coyotte508** [comment]
Hey! Repo is po-web now if you're interested.
