### ISSUE TITLE
Add a query option to set relay host/port

### ISSUE THREAD

**Issue by coyotte508** [po-devs/webclient#3]
A query option to select the relay host would be nice.

For example webclient.html?relay=server.pokemon-online.eu

That way when testing you don't have to type the relay again everytime you refresh the page, and also other servers can link to http://pokemon-online.eu/client/index.html?relay=other.server.ip

**Comment by HRDepartment** [comment]
I found this: http://www.bloggingdeveloper.com/post/JavaScript-QueryString-ParseGet-QueryString-with-Client-Side-JavaScript.aspx

**Comment by coyotte508** [comment]
looks good
