### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by coyotte508** [po-devs/webclient#32]
First brush of deity's design (more later) : 

(20:07) Deity: css/style.css http://pastebin.com/Dp3N6s8R
(20:07) Deity: css/reset.css http://pastebin.com/RF571K8k
(20:08) Deity: index.html http://pastebin.com/wmYXHTEC

**Comment by coyotte508** [comment]
As you can see from my design branch, and live here: http://nocdn.pokemon-online.eu/new-client/?server=default&autoconnect=true, I worked some!

Now the goal is to make it look like http://i2.minus.com/i6VK0e4PhJoKm.png (except channel tabs, they stay the same), and any contribution is welcome.

**Comment by HRDepartment** [comment]
You could modify some of the css for the channels tabs, though. They don't really fit the black design.

**Comment by coyotte508** [comment]
right, but for that we just need to edit a theme with jquery ui's theme roller.

what i meant is that the original screenshot doesn't have tabs and we do and we're keeping them

**Comment by coyotte508** [comment]
Find a better color for channel flashing too.

**Comment by coyotte508** [comment]
Deity taking care of this all
