### ISSUE TITLE
Channel links with a space in them don't work

### ISSUE THREAD

**Issue by coyotte508** [po-devs/webclient#37]
Try #Developer's Den or #Indigo Plateau. The link will show, but clicking on it doesn't do anything.

**Comment by HRDepartment** [comment]
Try to use escapeSlashes on it

**Comment by CrystalMoogle** [comment]
The problem is that it tries making you go to Developer's%20Den instead of Developer's Den. Replacing/decoding/escaping/whatever fixes it
escapeSlashes does nothing :v

**Comment by coyotte508** [comment]
Easier said than done :v

Prove it by making it work! :o

**Comment by HRDepartment** [comment]
Actually w/o escapeSlashes it wouldn't work either because browsers don't like 's or "s in URLs
