### ISSUE TITLE
Fix the space issue in query params for user name, default channel, ...

### ISSUE THREAD

**Issue by coyotte508** [po-devs/webclient#40]
/me wants to add Indigo Plateau to his autojoin but /me can't!

Probably find a function to do urldecode() in javascript and apply that to the result of the query?

!

**Comment by HRDepartment** [comment]
JavaScript comes equiped with functions for the job: unescape, decodeURI, decodeURIComponent

**Comment by coyotte508** [comment]
I'm sure any one working on solving the issue would have found that, the real issue is coding it
