### ISSUE TITLE
Html trainer info are not showing

### ISSUE THREAD

**Issue by coyotte508** [po-devs/webclient#61]
Trainer infos which contain html are loaded through an iframe (check index.js, updatePlayerInfo). It then calls "trainerinfo.html" with get parameters that dictates the content : https://github.com/po-devs/webclient/blob/gh-pages/trainerinfo.html

There seems to be an error there. You can use this example to reproduce the problem: (page shouldn't be blank)
http://po-devs.github.io/webclient/trainerinfo.html?content=PGRpdiBjbGFzcz0iaWZyYW1lLXRyYWluZXItaW5mbyI+PGNlbnRlcj5EYXkgYmVmb3JlIHllc3RlcmRheSBJIHNhdyBhIHJhYmJpdDxicj5ZZXN0ZXJkYXkgSSBzYXcgYSBkZWVyPGJyPkFuZCB0b2RheSwgeW91PGJyPjxpbWcgc3JjPSJodHRwOi8vcG9rZW1vbi1vbmxpbmUuZXUvaW1hZ2VzL3Bva2Vtb24vYmxhY2std2hpdGUvNDc4LnBuZyI+PC9jZW50ZXI+PC9kaXY+&css=ZmlsZTovLy9DOi9Vc2Vycy9Db21wYXEvY29kZS93ZWJjbGllbnQvY3NzL3dlYmNsaWVudC5jc3M=

**Comment by lamperi** [comment]
In your example,  CSS decodes into file:///C:/Users/Compaq/code/webclient/css/webclient.css so it is not possible to load it. Content contains invalid binary string so it is not possible to decode it.

**Comment by HRDepartment** [comment]
Fixed?
