### ISSUE TITLE
Escape html of non-html messages

### ISSUE THREAD

**Issue by coyotte508** [po-devs/webclient#7]
```
                } else if (cmd == "chat") {
                    var params = JSON.parse(data);
                    var msg = params.message;
```

Right after that add something like if (!params.html) { msg = escapeHtml(msg);}.

The escapeHtml function could also transform links by adding a href, like it does in the PO client, it'd be a nice addition

**Comment by HRDepartment** [comment]
Going to do this (posting here so no one else will waste their time on this).
